// The app itself, shared by every platform: screens, navigation and state, written once in
// Compose Multiplatform. Each platform app (Android/Fire TV in :app, desktop in :desktop, iOS
// in iosApp/) only adds what differs there: the video player, config storage and file access,
// passed in through the interfaces in the `platform` package.
import org.gradle.api.artifacts.result.ResolvedComponentResult
import org.gradle.api.artifacts.result.ResolvedDependencyResult

plugins {
    id("org.jetbrains.kotlin.multiplatform")
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.compose.multiplatform)
}

/**
 * Writes `CatalogVersions.kt`: every version from gradle/libs.versions.toml as a constant, so
 * the Licenses screen (`about/ThirdPartyComponents.kt`) names the versions the apps are built
 * with, and a Dependabot update changes them without anyone editing the list.
 *
 * Libraries that ship only because another one needs them (kotlinx-io with Ktor, Skiko with
 * Compose Multiplatform) have no version in the catalog. Their constants ([transitiveModules]:
 * constant name to `group:name`, or just `group`) take the version Gradle resolved for the
 * desktop app ([rootComponent]), so they follow the library that brings them in.
 */
abstract class GenerateCatalogVersions : DefaultTask() {
    @get:Input
    abstract val versions: MapProperty<String, String>

    @get:Input
    abstract val transitiveModules: MapProperty<String, String>

    @get:Input
    abstract val rootComponent: Property<ResolvedComponentResult>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    /** Version of every module in the resolved graph, keyed by `group:name`. */
    private fun resolvedModules(): Map<String, String> {
        val modules = sortedMapOf<String, String>()
        val seen = mutableSetOf<ResolvedComponentResult>()
        val pending = ArrayDeque<ResolvedComponentResult>().apply { add(rootComponent.get()) }
        while (pending.isNotEmpty()) {
            val component = pending.removeFirst()
            if (!seen.add(component)) continue
            component.moduleVersion?.let { modules.putIfAbsent("${it.group}:${it.name}", it.version) }
            component.dependencies.filterIsInstance<ResolvedDependencyResult>().forEach { pending.add(it.selected) }
        }
        return modules
    }

    @TaskAction
    fun generate() {
        val transitive = transitiveModules.get()
        val resolved = if (transitive.isEmpty()) emptyMap() else resolvedModules()
        val transitiveVersions = transitive.mapValues { (name, module) ->
            resolved.entries.firstOrNull { (key, _) -> key == module || key.substringBefore(':') == module }?.value
                ?: throw GradleException("$module (for CatalogVersions.$name) is not in the resolved dependencies any more")
        }
        val catalogVersions = versions.get().mapKeys { (alias, _) ->
            alias.replace(Regex("[^A-Za-z0-9]+(.)")) { it.groupValues[1].uppercase() }
        }
        val clash = catalogVersions.keys.intersect(transitiveVersions.keys)
        if (clash.isNotEmpty()) throw GradleException("Catalog versions and transitive modules both define $clash")
        val constants = (catalogVersions + transitiveVersions).toSortedMap().entries.joinToString("\n") { (name, version) ->
            "    const val $name = \"$version\""
        }
        val file = outputDir.file("io/github/vandosketch/camgrid/about/CatalogVersions.kt").get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by :shared:generateCatalogVersions from gradle/libs.versions.toml. Do not edit.
            |package io.github.vandosketch.camgrid.about
            |
            |/**
            | * The versions table of gradle/libs.versions.toml, plus the resolved versions of libraries
            | * that come in through others, generated at build time.
            | */
            |internal object CatalogVersions {
            |$constants
            |}
            |""".trimMargin(),
        )
    }
}

val generateCatalogVersions by tasks.registering(GenerateCatalogVersions::class) {
    val catalog = versionCatalogs.named("libs")
    versions.set(catalog.versionAliases.associateWith { catalog.findVersion(it).get().requiredVersion })
    transitiveModules.set(
        mapOf(
            // Comes with Ktor.
            "kotlinxIo" to "org.jetbrains.kotlinx:kotlinx-io-core",
            // Comes with Compose Multiplatform (skiko on iOS, skiko-awt on desktop: one version).
            "skiko" to "org.jetbrains.skiko",
        ),
    )
    // The desktop app's graph has both; the iOS and Android apps use the same Ktor and Compose.
    rootComponent.set(configurations.named("desktopRuntimeClasspath").flatMap { it.incoming.resolutionResult.rootComponent })
    outputDir.set(layout.buildDirectory.dir("generated/catalogVersions/commonMain/kotlin"))
}

kotlin {
    compilerOptions {
        optIn.addAll("kotlin.uuid.ExperimentalUuidApi", "kotlin.io.encoding.ExperimentalEncodingApi")
    }

    android {
        namespace = "io.github.vandosketch.camgrid.shared"
        compileSdk = 37
        minSdk = 25
        androidResources { enable = true }
    }
    jvm("desktop")
    listOf(iosArm64(), iosSimulatorArm64()).forEach { target ->
        target.binaries.framework {
            baseName = "CamGridShared"
            isStatic = true
            export(project(":core"))
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateCatalogVersions)
        }
        commonMain.dependencies {
            api(project(":core"))
            api(libs.cmp.runtime)
            api(libs.cmp.foundation)
            api(libs.cmp.ui)
            api(libs.cmp.material3)
            implementation(libs.cmp.material.icons)
            // Back key / gesture on desktop and iOS (Android uses androidx.activity's BackHandler).
            implementation(libs.navigationevent.compose.mp)
            implementation(libs.cmp.resources)
            api(libs.lifecycle.viewmodel.compose.mp)
            implementation(libs.lifecycle.runtime.compose.mp)
            implementation(libs.coroutines.core)
            // api: the Android app's WebRTC player uses WhepClient with the shared HttpClient.
            api(libs.ktor.client.core)
        }
        androidMain.dependencies {
            // HttpURLConnection underneath, like the app used before.
            implementation(libs.ktor.client.android)
            implementation(libs.activity.compose)
        }
        getByName("desktopMain").dependencies {
            implementation(libs.ktor.client.java)
        }
        getByName("desktopTest").dependencies {
            // Skiko's native library: Compose resources ask it for the system theme.
            implementation(compose.desktop.currentOs)
            // Compose UI tests of the shared screens, run on the JVM (runComposeUiTest).
            implementation(libs.cmp.ui.test)
            // Decodes the transfer QR code in tests; not part of any app.
            implementation(libs.zxing.core)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.coroutines.test)
            implementation(libs.ktor.client.mock)
        }
    }
}

// The drift guard (about/DependencyInventoryTest) reads gradle/libs.versions.toml, iosApp/project.yml
// and NOTICE from the repository.
tasks.named<Test>("desktopTest") {
    systemProperty("camgrid.rootDir", rootDir.absolutePath)
    inputs.files(
        rootProject.file("gradle/libs.versions.toml"),
        rootProject.file("iosApp/project.yml"),
        rootProject.file("NOTICE"),
        rootProject.file("LICENSE"),
    ).withPathSensitivity(PathSensitivity.RELATIVE)
}

compose.resources {
    publicResClass = false
    packageOfResClass = "io.github.vandosketch.camgrid.shared.resources"
}
