// The app itself, shared by every platform: screens, navigation and state, written once in
// Compose Multiplatform. Each platform app (Android/Fire TV in :app, desktop in :desktop, iOS
// in iosApp/) only adds what differs there: the video player, config storage and file access,
// passed in through the interfaces in the `platform` package.
plugins {
    id("org.jetbrains.kotlin.multiplatform")
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.compose.multiplatform)
}

/**
 * Writes `CatalogVersions.kt`: every version from gradle/libs.versions.toml as a constant, so
 * the Licenses screen (`about/ThirdPartyComponents.kt`) names the versions the apps are built
 * with, and a Dependabot update changes them without anyone editing the list.
 */
abstract class GenerateCatalogVersions : DefaultTask() {
    @get:Input
    abstract val versions: MapProperty<String, String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val constants = versions.get().toSortedMap().entries.joinToString("\n") { (alias, version) ->
            val name = alias.replace(Regex("[^A-Za-z0-9]+(.)")) { it.groupValues[1].uppercase() }
            "    const val $name = \"$version\""
        }
        val file = outputDir.file("io/github/vandosketch/camgrid/about/CatalogVersions.kt").get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by :shared:generateCatalogVersions from gradle/libs.versions.toml. Do not edit.
            |package io.github.vandosketch.camgrid.about
            |
            |/** The versions table of gradle/libs.versions.toml, generated at build time. */
            |internal object CatalogVersions {
            |$constants
            |}
            |""".trimMargin(),
        )
    }
}

val generateCatalogVersions by tasks.registering(GenerateCatalogVersions::class) {
    val catalog = versionCatalogs.named("libs")
    versions.set(catalog.versionAliases.associateWith { catalog.findVersion(it).get().requiredVersion })
    outputDir.set(layout.buildDirectory.dir("generated/catalogVersions/commonMain/kotlin"))
}

kotlin {
    compilerOptions {
        optIn.addAll("kotlin.uuid.ExperimentalUuidApi", "kotlin.io.encoding.ExperimentalEncodingApi")
    }

    android {
        namespace = "io.github.vandosketch.camgrid.shared"
        compileSdk = 37
        minSdk = 25
        androidResources { enable = true }
    }
    jvm("desktop")
    listOf(iosArm64(), iosSimulatorArm64()).forEach { target ->
        target.binaries.framework {
            baseName = "CamGridShared"
            isStatic = true
            export(project(":core"))
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateCatalogVersions)
        }
        commonMain.dependencies {
            api(project(":core"))
            api(libs.cmp.runtime)
            api(libs.cmp.foundation)
            api(libs.cmp.ui)
            api(libs.cmp.material3)
            implementation(libs.cmp.material.icons)
            // Back key / gesture on desktop and iOS (Android uses androidx.activity's BackHandler).
            implementation(libs.navigationevent.compose.mp)
            implementation(libs.cmp.resources)
            api(libs.lifecycle.viewmodel.compose.mp)
            implementation(libs.lifecycle.runtime.compose.mp)
            implementation(libs.coroutines.core)
            // api: the Android app's WebRTC player uses WhepClient with the shared HttpClient.
            api(libs.ktor.client.core)
        }
        androidMain.dependencies {
            // HttpURLConnection underneath, like the app used before.
            implementation(libs.ktor.client.android)
            implementation(libs.activity.compose)
        }
        getByName("desktopMain").dependencies {
            implementation(libs.ktor.client.java)
        }
        getByName("desktopTest").dependencies {
            // Skiko's native library: Compose resources ask it for the system theme.
            implementation(compose.desktop.currentOs)
            // Compose UI tests of the shared screens, run on the JVM (runComposeUiTest).
            implementation(libs.cmp.ui.test)
            // Decodes the transfer QR code in tests; not part of any app.
            implementation(libs.zxing.core)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.coroutines.test)
            implementation(libs.ktor.client.mock)
        }
    }
}

// The drift guard (about/DependencyInventoryTest) reads gradle/libs.versions.toml, iosApp/project.yml
// and NOTICE from the repository.
tasks.named<Test>("desktopTest") {
    systemProperty("camgrid.rootDir", rootDir.absolutePath)
    inputs.files(
        rootProject.file("gradle/libs.versions.toml"),
        rootProject.file("iosApp/project.yml"),
        rootProject.file("NOTICE"),
        rootProject.file("LICENSE"),
    ).withPathSensitivity(PathSensitivity.RELATIVE)
}

compose.resources {
    publicResClass = false
    packageOfResClass = "io.github.vandosketch.camgrid.shared.resources"
}
